### PR TITLE
1.9.3

### PR DESCRIPTION
**Pull request by stade**
~~Caveat:~~

~~-Uses LIBRDKAFKA_VERSION=0.9.3-1. (only one available in official repos).  Which is different~~ ~~from: https://github.com/comptelfwd/golang-kafkaclient/blob/master/Dockerfile#L4. If this is major~~ ~~issue then we have to manually setup same version to the image.~~

Backports libdrkafka 0.11.3-1~bpo9+1 from stretch-backports.

### CODE REVIEW

**Comment by ilbambino** [comment]
They are very different, so yes I think we need to use the same version. Many things fixed since that version

**Comment by javier-sanz** [comment]
Plus our Golang  Kafka wrapper is not compatible with that version. I will complain about not having the right symbols.

**Comment by stade** [comment]
Ok seems to be available in backports: https://packages.debian.org/stretch-backports/librdkafka1.

**Comment by stade** [comment]
@javier-sanz and @ilbambino is https://github.com/edenhill/librdkafka/releases/tag/v0.11.3 11.3 close enough it's available in backports: https://packages.debian.org/stretch-backports/librdkafka1.

If it's not then we need to compile it ourself which I would like to pretty much avoid.

**Pull request merged**
